name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Đồng bộ hóa mã nguồn từ kho lưu trữ về máy ảo
        uses: actions/checkout@v3

      - name: 2. Thiết lập môi trường chạy JDK 25 Eclipse Temurin chuẩn
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Biên dịch và tự động kiểm tra định dạng mã nguồn kết hợp Unit Test
        run: mvn clean test
